---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: set timezone
      timezone: 
        name: Europe/Moscow
    - name: setup locale
      copy:
        src: files/environment
        dest: /etc/environment
        owner: root
        group: root
        mode: 0644
    - name: install packages
      yum:
        name: ['wget','unzip','git','lsof','tcpdump','jq','vim','lvm2']
        state: present
...