---
# tasks file for add_prometheus

- include: install.yml
  become: true
  tags:
    - install

- include: configure.yml
  become: true
  tags:
    - configure

- name: ensure prometheus service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  tags:
    - run
...
