---
# tasks file for haproxy
- name: haproxy install
  yum:
    name: 
      - haproxy
      - policycoreutils
    state: latest

- name: Add haproxy.conf /etc/haproxy directory
  template: 
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: Add haproxy.conf /etc/rsyslog.d directory for logging
  template: 
    src: haproxy.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf
    owner: root
    group: root
    mode: 0644

- name: SELinux for HAproxy
  command: setsebool -P haproxy_connect_any=1

- name: Set haproxy as a service
  systemd:
    name: haproxy
    enabled: yes
    state: started
    masked: no

- name: Restart rsyslog service
  systemd:
    name: rsyslog
    state: restarted
...